# Generated by Django 4.0.2 on 2022-02-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inv_Brands',
            fields=[
                ('BId', models.AutoField(primary_key=True, serialize=False)),
                ('BName', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inv_Category',
            fields=[
                ('CId', models.AutoField(primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inv_Items',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('CId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.inv_category')),
            ],
        ),
    ]
