# Generated by Django 4.0.2 on 2022-02-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSetup',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('RPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('OPId', models.AutoField(primary_key=True, serialize=False)),
                ('OPDate', models.DateTimeField()),
                ('BatchNo', models.CharField(max_length=100)),
                ('Qty', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.itemsetup')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('PId', models.AutoField(primary_key=True, serialize=False)),
                ('PDate', models.DateTimeField()),
                ('BatchNo', models.CharField(max_length=100)),
                ('Qty', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.itemsetup')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('SId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=500)),
                ('Qty', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.itemsetup')),
            ],
        ),
        migrations.RenameModel(
            old_name='Inv_Brands',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='Inv_Category',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Inv_Items',
        ),
        migrations.AddField(
            model_name='itemsetup',
            name='BId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.brands'),
        ),
        migrations.AddField(
            model_name='itemsetup',
            name='CId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.category'),
        ),
    ]
