# Generated by Django 4.0.2 on 2022-02-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_itemsetup_opening_purchase_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsetup',
            name='BId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.brands', verbose_name='BId'),
        ),
        migrations.AlterField(
            model_name='itemsetup',
            name='CId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.category', verbose_name='CId'),
        ),
    ]
