# Generated by Django 4.0.2 on 2022-02-15 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_alter_itemsetup_bid_alter_itemsetup_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsetup',
            name='BId',
            field=models.ForeignKey(db_column='BId', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.brands'),
        ),
        migrations.AlterField(
            model_name='itemsetup',
            name='CId',
            field=models.ForeignKey(db_column='CId', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.category'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='ItemId',
            field=models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.itemsetup'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ItemId',
            field=models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.itemsetup'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ItemId',
            field=models.ForeignKey(db_column='ItemId', on_delete=django.db.models.deletion.DO_NOTHING, to='Inventory.itemsetup'),
        ),
    ]
